# GitHub workflow file for Node.js CI

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM clean install
      run: npm ci
    - name: NPM build and check
      run: |
        npm run build --if-present
        npm run check --if-present
    - name: NPM test
      run: npm test
      env:
        CI: true
